### ISSUE TITLE
Unexpected error thrown when the browser does not support `navigator.mediaDevices`

### ISSUE THREAD

**Issue by glen-cheney** [MABelanger/jslib-html5-camera-photo#33]
When this library is used in jest with jsdom as the environment, or a non-https context in some browsers (Chrome, Safari), it throws an unexpected error. Using an alias for `localhost` is fairly common. I don't expect the camera to work in JSDom, and I did expect an error, but not this error.

```
error starting camera TypeError: Cannot read property 'getSupportedConstraints' of undefined
        at Function.width (/Users/myproject/path/node_modules/jslib-html5-camera-photo/build/webpack:/src/lib/MediaServices/index.js:102:24)
        at Function.this (/Users/myproject/path/node_modules/jslib-html5-camera-photo/build/webpack:/src/lib/MediaServices/index.js:122:8)
        at e.sizeFactor (/Users/myproject/path/node_modules/jslib-html5-camera-photo/build/webpack:/src/lib/index.js:55:14)
        at /Users/myproject/path/node_modules/jslib-html5-camera-photo/build/webpack:/src/lib/index.js:165:7
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It looks like you're using a polyfilled version of `navigator.mediaDevices` with the `getNavigatorMediaDevices` function, but the function which causes the error does not use `getNavigatorMediaDevices`. Instead, it uses `navigator.mediaDevices` directly:

https://github.com/MABelanger/jslib-html5-camera-photo/blob/4a776199313e0a31bbbdcece3c49a96c979052e8/src/lib/MediaServices/index.js#L91

**Comment by Liam-PVTL** [comment]
Bump! Running into an issue using the package because of this

**Comment by MABelanger** [comment]
@Vestride ,
Thank for reporting, it should be fix.
