### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.

### ISSUE THREAD

**Issue by GodayMax** [MABelanger/jslib-html5-camera-photo#82]
seems some deperacated api issue;
but i do not have this problem visiting demo page, very strange....

Camera not started! TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at e.value (pages-additional-form-pe_checkin.js:2745:10724)
    at e.value (pages-additional-form-pe_checkin.js:2745:11356)
    at pages-additional-form-pe_checkin.js:2745:10037

**Comment by dmitrijs-pavlovs-dev** [comment]
I had the same error. Turns out the video html element has to be. Make sure that the html element that you attach the video to is like this `<video id="videoId" autoplay="true" playsInline ></video>`
